<?php

/*
 * Implementation of hook_form_alter()
 */
//function yl_36_form_alter(&$form, &$form_state, $form_id) {
//  $form['yl_36_phone'] = [
//    '#type' => 'tel',
//    '#title' => t('Phone'),
//    '#required' => TRUE,
//  ];
//
//  if (strlen($form_state->getValue('yl_36_phone')) < 11) {
//    $form_state->setErrorByName('phone_number', t('The phone number is too short. Please enter a full phone number.'));
//  }
//}
