<?php

use Drupal\yl_configuration_form\Form\ModuleConfigurationForm;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function yl_configuration_form_node_presave(EntityInterface $entity) {
  $config = \Drupal::config('yl_configuration_form.admin_settings');
  $country_name = $config->get('country_var');

  if ($entity->getEntityType()->id() == 'node' && isset($country_name)) {
    $list_of_countries = ModuleConfigurationForm::getListOfCountries();
    $entity->setTitle($entity->getTitle() . ' ' . $list_of_countries[$country_name]);
  }
}
